import ProjectDescription

let workspace = Workspace(
    name: "mentory",
    projects: [
        "MentoryApp",
        "MentoryDevice",
        "MentoryShared",
        "MentoryDB",
        "MentoryLLM",
    ],
    schemes: [
        .scheme(
            name: "MentoryApp",
            buildAction: .buildAction(
                targets: [
                    .project(path: "MentoryApp", target: "MentoryApp"),
                ]
            ),
            testAction: .targets(
                [
                    .testableTarget(
                        target: .project(path: "MentoryApp", target: "MentoryTests"),
                        parallelization: .disabled
                    ),
                    .testableTarget(
                        target: .project(path: "MentoryDB", target: "NewMentoryDBFakeTests"),
                        parallelization: .disabled
                    ),
                ],
                expandVariableFromTarget: .project(path: "MentoryApp", target: "MentoryApp")
            ),
            runAction: .runAction(
                executable: .project(path: "MentoryApp", target: "MentoryApp"),
                expandVariableFromTarget: .project(path: "MentoryApp", target: "MentoryApp")
            ),
            archiveAction: .archiveAction(configuration: .release),
            profileAction: .profileAction(
                executable: .project(path: "MentoryApp", target: "MentoryApp")
            ),
            analyzeAction: .analyzeAction(configuration: .debug)
        ),
    ],
    additionalFiles: [
        "README.md",
    ],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled
    )
)
